### Splitting Datasets
- Splitting the data into Traning and Testing Sets
- **1. Traning Data**(The observations in the traning set form the expreience that the algorithm uses to learn.)
- **1. Traning Data**(The test set is a set of aobservations used to evaluate the preformance of te model using some preformance metric.)

**Complete Dataset**
- 1. Training Datasets(**Large size(70-80%)**)
- 2. Testing Datasets(**small size(15-20%)**)

**How to split the data into Training and Testing sets ?**
- Manually split the data
- From Sklearn.Model_selection import train_test_split.
- sometimes the data is already split into training and test dataset.

# Partical

- step 1. Upload dataset
- step 2. Manual split
- step 3. split using sklearn.model_selection

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("iris.csv")

In [5]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

**Manual**
- Input = x
- Output = y

In [12]:
x = data.iloc[:,:5]

In [13]:
x

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [15]:
y = data.iloc[:,5]

In [16]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [17]:
# Training and Testing
x_train = x.iloc[:100]

In [18]:
x_test = x.iloc[100:]

In [19]:
x_train

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0     1            5.1           3.5            1.4           0.2
1     2            4.9           3.0            1.4           0.2
2     3            4.7           3.2            1.3           0.2
3     4            4.6           3.1            1.5           0.2
4     5            5.0           3.6            1.4           0.2
..  ...            ...           ...            ...           ...
95   96            5.7           3.0            4.2           1.2
96   97            5.7           2.9            4.2           1.3
97   98            6.2           2.9            4.3           1.3
98   99            5.1           2.5            3.0           1.1
99  100            5.7           2.8            4.1           1.3

[100 rows x 5 columns]

In [20]:
x_test

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
100  101            6.3           3.3            6.0           2.5
101  102            5.8           2.7            5.1           1.9
102  103            7.1           3.0            5.9           2.1
103  104            6.3           2.9            5.6           1.8
104  105            6.5           3.0            5.8           2.2
105  106            7.6           3.0            6.6           2.1
106  107            4.9           2.5            4.5           1.7
107  108            7.3           2.9            6.3           1.8
108  109            6.7           2.5            5.8           1.8
109  110            7.2           3.6            6.1           2.5
110  111            6.5           3.2            5.1           2.0
111  112            6.4           2.7            5.3           1.9
112  113            6.8           3.0            5.5           2.1
113  114            5.7           2.5            5.0           2.0
114  115            5.8           2.8            5.1           2.4
115  116            6.4           3.2            5.3           2.3
116  117            6.5           3.0            5.5           1.8
117  118            7.7           3.8            6.7           2.2
118  119            7.7           2.6            6.9           2.3
119  120            6.0           2.2            5.0           1.5
120  121            6.9           3.2            5.7           2.3
121  122            5.6           2.8            4.9           2.0
122  123            7.7           2.8            6.7           2.0
123  124            6.3           2.7            4.9           1.8
124  125            6.7           3.3            5.7           2.1
125  126            7.2           3.2            6.0           1.8
126  127            6.2           2.8            4.8           1.8
127  128            6.1           3.0            4.9           1.8
128  129            6.4           2.8            5.6           2.1
129  130            7.2           3.0            5.8           1.6
130  131            7.4           2.8            6.1           1.9
131  132            7.9           3.8            6.4           2.0
132  133            6.4           2.8            5.6           2.2
133  134            6.3           2.8            5.1           1.5
134  135            6.1           2.6            5.6           1.4
135  136            7.7           3.0            6.1           2.3
136  137            6.3           3.4            5.6           2.4
137  138            6.4           3.1            5.5           1.8
138  139            6.0           3.0            4.8           1.8
139  140            6.9           3.1            5.4           2.1
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

In [21]:
y_train = y.iloc[:100]
y_test = y.iloc[100:]

In [22]:
y_train

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
           ...
95    Iris-versicolor
96    Iris-versicolor
97    Iris-versicolor
98    Iris-versicolor
99    Iris-versicolor
Name: Species, Length: 100, dtype: object

In [23]:
y_test

100    Iris-virginica
101    Iris-virginica
102    Iris-virginica
103    Iris-virginica
104    Iris-virginica
105    Iris-virginica
106    Iris-virginica
107    Iris-virginica
108    Iris-virginica
109    Iris-virginica
110    Iris-virginica
111    Iris-virginica
112    Iris-virginica
113    Iris-virginica
114    Iris-virginica
115    Iris-virginica
116    Iris-virginica
117    Iris-virginica
118    Iris-virginica
119    Iris-virginica
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iris-virginica
135    Iris-virginica
136    Iris-virginica
137    Iris-virginica
138    Iris-virginica
139    Iris-virginica
140    Iris-virginica
141    Iris-virginica
142    Iris-virginica
143    Iris-virginica
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, dtype: object

# 2nd (Method-Sklearn)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 30, random_state = 1)

In [28]:
x_train

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
91    92            6.1           3.0            4.6           1.4
135  136            7.7           3.0            6.1           2.3
69    70            5.6           2.5            3.9           1.1
128  129            6.4           2.8            5.6           2.1
114  115            5.8           2.8            5.1           2.4
..   ...            ...           ...            ...           ...
133  134            6.3           2.8            5.1           1.5
137  138            6.4           3.1            5.5           1.8
72    73            6.3           2.5            4.9           1.5
140  141            6.7           3.1            5.6           2.4
37    38            4.9           3.1            1.5           0.1

[120 rows x 5 columns]

In [29]:
y_test

14         Iris-setosa
98     Iris-versicolor
75     Iris-versicolor
16         Iris-setosa
131     Iris-virginica
56     Iris-versicolor
141     Iris-virginica
44         Iris-setosa
29         Iris-setosa
120     Iris-virginica
94     Iris-versicolor
5          Iris-setosa
102     Iris-virginica
51     Iris-versicolor
78     Iris-versicolor
42         Iris-setosa
92     Iris-versicolor
66     Iris-versicolor
31         Iris-setosa
35         Iris-setosa
90     Iris-versicolor
84     Iris-versicolor
77     Iris-versicolor
40         Iris-setosa
125     Iris-virginica
99     Iris-versicolor
33         Iris-setosa
19         Iris-setosa
73     Iris-versicolor
146     Iris-virginica
Name: Species, dtype: object